# Generated by Django 5.1 on 2026-05-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_search_indexes'),
        ('projects', '0002_add_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.cycle'),
        ),
    ]
