# Generated by Django 5.1 on 2026-05-26 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='📋', max_length=10)),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=7)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['name'],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
